modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="simpleraces"
version="1.0.2"
displayName="Maledictom RPG Races"
displayURL="https://www.curseforge.com/members/minobanana/projects"
credits="Jabroni"
authors="Jabroni"
description="Pick From Fantasy Races"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.simpleraces]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.simpleraces]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpleraces]]
    modId="pehkui"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpleraces]]
    modId="irons_spellbooks"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration