modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="mixins.simpleraces.json"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kleidersplayerrenderer"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="pehkui"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="playeranimator"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="caelus"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="irons_spellbooks"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
