
["Class Select"]
	#Force player to pick a class after joining
	force_pick = true
	#Message players who haven't selected a class
	join_message = true
	#Ability to deselect classes (survival) via /classreset
	deselect = false
	#Enter Join Message Text
	join_message_text = "Click the Assigned Key [M] To Open the RPG Race Selection Menu"

["Elf Class Attributes"]
	#Set elf max health
	elf_max_health = 16.0
	#Add glowing effect when drawing bow
	elf_bow_sight = true
	#Whether or not elves can eat meat without being poisoned
	elf_meat_restrict = true
	#Bonus percent of damage elves deal with bows
	#Range: -1.0 ~ 2.0
	elf_bow_multiplyer = 0.35

["Orc Class Attributes"]
	#Penalty to orc attack damage (negative value for decrease, e.g. -0.4 for 60% damage)
	#Range: -1.0 ~ 0.0
	orc_damage_penalty = -0.4
	#Penalty to orc magic damage
	#Range: -1.0 ~ 0.0
	orc_magic_damage_penalty = -0.6
	#Increased strength on low health
	#Range: 0.0 ~ 1.0
	orc_damage_rage = 0.3
	#Duration in ticks of debuff after fervor fades (default 100 for 5 seconds)
	#Range: 0 ~ 600
	orc_fervor_debuff_duration = 100
	#Level of slowdown effect after fervor fades (e.g., 2 for strong slowdown)
	#Range: 0 ~ 5
	orc_fervor_slowdown_level = 2
	#Incoming damage multiplier during debuff after fervor fades (e.g., 1.2 for 20% more damage)
	#Range: 1.0 ~ 2.0
	orc_fervor_incoming_damage_multiplier = 1.2

["Dwarf Class Attributes"]
	#Increased mining speed underground
	dwarf_haste = true
	dwarf_max_health = 10.0
	#Level of resistance effect
	dwarf_res_level = 0.0
	#Dwarf gains nightvision + haste 2 at subzero levels (underground only)
	dwarf_subzero_effects = true
	#Dwarf cant use bows
	dwarf_bow_restrict = true

["Merfolk Class Attributes"]
	#Swim speed
	merfolk_swim_speed = 2.0
	#Whether or not the conduit effect is applied
	merfolk_conduit_effect = true
	#Penalty to merfolk damage on surface (negative value for decrease, e.g. -0.4 for 60% damage)
	#Range: -1.0 ~ 0.0
	merfolk_surface_penalty = -0.33
	#Increased merfolk damage in water
	#Range: 0.0 ~ 1.0
	merfolk_water_damage = 0.2
	#Penalty for merfolk's movement speed on surface
	merfolk_surface_speed = -0.35
	#Merfolk max health on surface
	merfolk_max_health_surface = 10.0
	#Health boost multiplier for merfolk in water (e.g. 1.0 for +100% health)
	merfolk_water_health_boost = 1.0
	#Dig speed level for merfolk in water (Haste level, 0 = no, 1 = Haste I)
	#Range: 0 ~ 5
	merfolk_dig_speed_water = 1

["Drakonid Class Attributes"]
	#Apply fire aspect to attacks
	drak_fire = true
	#Whether or not to resist damage from fire sources
	drak_fire_res = true
	#Drakonid (gold/leather armor) melts
	drakonid_armor_mel = true
	#Drakonid hurt by water
	drakonid_water_hurt = true
	#Heat generated per attack
	drakonid_heat_per_attack = 4
	#Maximum heat level before overheating
	drakonid_max_heat = 100
	#Time in seconds of overheating
	drakonid_overheat_time = 400
	#Drakonid fall damage multiplier
	drakonid_fall_multiply = 0.8
	#Time in seconds fire duration after overheating
	drakonid_overheat_fire_time = 5

["Fairy Class Attributes"]
	#Fairy fall damage multiplier
	fairy_fall_multiply = 0.75
	#Fairy fly speed multiplier
	fairy_fly_speed_multiply = 1.0
	#Fairy max health
	fairy_max_health = 8.0
	#Fairy flying time(seconds)
	fairy_max_flying_time = 10

[Cosmetics]
	elf_ears = true
	orc_tusks = true
	merfolk_form = true
	dwarf_resize = true
	elf_resize = true
	orc_resize = true

["Werewolf Class Attributes"]
	#Werewolf damage bonus in beast form (multiplicative)
	#Range: 0.0 ~ 1.0
	werewolf_beast_damage_bonus = 0.2
	#Werewolf damage penalty in human form (multiplicative)
	#Range: -1.0 ~ 0.0
	werewolf_human_damage_penalty = -0.3
	#Werewolf speed bonus in beast form (multiplicative)
	#Range: 0.0 ~ 1.0
	werewolf_beast_speed_bonus = 0.2
	#Werewolf speed penalty in human form (multiplicative)
	#Range: -1.0 ~ 0.0
	werewolf_human_speed_penalty = -0.3
	#Werewolf health bonus in beast form (additive)
	#Range: 0.0 ~ 20.0
	werewolf_beast_health_bonus = 4.0
	#Werewolf health penalty in human form (additive)
	#Range: -20.0 ~ 0.0
	werewolf_human_health_penalty = -4.0

["Serpentine Class Attributes"]
	#Serpentin max health
	serpentin_max_health = 20.0
	#Damage multiplier for serpentin when target has debuff
	#Range: 1.0 ~ 2.0
	serpentin_damage_bonus_with_debuff = 1.25
	#Damage multiplier for serpentin when target has no debuff
	#Range: 0.0 ~ 1.0
	serpentin_damage_penalty_without_debuff = 0.65
	#Potion duration multiplier for serpentin
	#Range: 1.0 ~ 3.0
	serpentin_potion_duration_multiplier = 1.5
	#Amplifier bonus for Strength potion
	#Range: 0 ~ 5
	serpentin_strength_amplifier_bonus = 1
	#Amplifier bonus for Speed potion
	#Range: 0 ~ 5
	serpentin_speed_amplifier_bonus = 1
	#Amplifier bonus for Jump potion
	#Range: 0 ~ 5
	serpentin_jump_amplifier_bonus = 2

["Arachna Class Attributes"]
	#Arachna max health
	aracha_max_health = 16.0
	#Duration of slowdown effect in water for aracha
	#Range: 1 ~ 100
	aracha_water_slowdown_duration = 2
	#Amplifier of slowdown in water
	#Range: 0 ~ 10
	aracha_water_slowdown_amplifier = 2
	#Duration of slowdown with heavy armor
	#Range: 1 ~ 100
	aracha_heavy_armor_slowdown_duration = 3
	#Amplifier of slowdown with heavy armor
	#Range: 0 ~ 10
	aracha_heavy_armor_slowdown_amplifier = 0
	#Number of bites to trigger fangs and poison
	#Range: 1 ~ 10
	aracha_bite_count_threshold = 3
	#Duration of poison effect after bites
	#Range: 20 ~ 200
	aracha_poison_duration = 40
	#Amplifier of poison effect
	#Range: 0 ~ 5
	aracha_poison_amplifier = 0
	#Fire damage multiplier for aracha
	#Range: 1.0 ~ 3.0
	aracha_fire_damage_multiplier = 1.5

["Halfdead Class Attributes"]
	#Halfdead max health
	halfdead_max_health = 23.0
	#Heal multiplier for halfdead
	#Range: 0.0 ~ 1.0
	halfdead_heal_multiplier = 0.2
	#Heal amount on kill for halfdead
	#Range: 0.0 ~ 40.0
	halfdead_heal_on_kill = 2.0
	#Duration of death mark effect in ticks
	#Range: 100 ~ 600
	halfdead_death_mark_duration = 200
	#Damage bonus vs undead for halfdead
	#Range: 1.0 ~ 2.0
	halfdead_damage_bonus_vs_undead = 1.2
	#Damage reduction when attacker has death mark
	#Range: 0.0 ~ 1.0
	halfdead_damage_reduction_from_mark = 0.67
	#Damage increase to marked targets
	#Range: 1.0 ~ 2.0
	halfdead_damage_increase_to_marked = 1.33
	#Radius to search for nearby entities to apply death mark
	#Range: 1.0 ~ 50.0
	halfdead_death_mark_radius = 10.0

[Others]
	#Damage penalty for ranged weapons (bows/crossbows) for non-elf races (multiplicative, e.g., -0.6 for 60% less damage)
	#Range: -1.0 ~ 0.0
	ranged_weapon_damage_penalty = -0.6

